### ISSUE TITLE
float8[] array has first value parsed as NaN

### ISSUE THREAD

**Issue by ryanhestin** [bendrucker/postgres-array#1]
See [this](https://github.com/brianc/node-postgres/issues/845) for more info on issue.

I see node-postgres seems to use this parser, which is why I CC'ed an issue here.

**Comment by bendrucker** [comment]
Would love a PR if you can since it sounds like you've already spent a good chunk of time researching this

**Comment by hestinr12** [comment]
I haven't actually got the chance to dig in and see what may be the cause. It took me a couple hours last night just to figure out what was even happening >.<

I'll spend some time tonight checking into it though, no one on the other issue thread has brought it up. Are fixed arrays that uncommon, or should I just stop slacking and use PostGIS? XD

**Comment by ryanhestin** [comment]
The first element of a postgres array is at `[1]`, not `[0]`.

Sorry to waste your time :)

**Comment by bendrucker** [comment]
No worries! Thanks for letting me know.
