### ISSUE TITLE
Parsing of NULL/null/NuLl is different than in PG source code

### ISSUE THREAD

**Issue by dko-slapdash** [bendrucker/postgres-array#17]
Here:

https://github.com/bendrucker/postgres-array/blob/d29dbdfe86404be7592688b8968906d366f0efd8/index.js#L19

Currently, the library parses `'{null}'` incorrectly as `["null"]` instead of `[null]`.

We could've used toLowerCase() to follow the exactly same rules that are followed by PG itself. Example:

![CleanShot 2023-06-29 at 13 11 27@2x](https://github.com/bendrucker/postgres-array/assets/46383452/fede7807-61a0-4882-a5e0-3b981f15c1b0)

PG source code:

![CleanShot 2023-06-29 at 13 12 18@2x](https://github.com/bendrucker/postgres-array/assets/46383452/322a61ea-9119-4310-b572-122469a70df7)

**Comment by bendrucker** [comment]
The goal of the library is to parse what Postgres returns, and not all the inputs it supports. As your example shows, the output is always `NULL`. While I'd probably accept a PR to make it behave that you want, I don't consider this a bug.

**Comment by dko-slapdash** [comment]
PostgreSQL source code itself has a flexible parser. Can't imagine why postgres-array parser should be different in logic than PostgreSQL parser (actually I have a suspicion, but the reason seems to be not technical).
