### ISSUE TITLE
[0:2]={1,2,3} is parsed as [ '[0:2]=1', '2', '3' ]

### ISSUE THREAD

**Issue by ahultgren** [bendrucker/postgres-array#2]
Expected: `['1', '2', '3']`

I have no idea why postgres is returning this particular syntax for my query, but I think it should be supported. I would have submitted a pull-request, but unfortunately I couldn't understand of your code :)

A temporary workaround is btw to wrap the array in array_to_json, but performance seems to be awful.

**Comment by bendrucker** [comment]
Code is pulled out through different repos a bunch of times. I don't have time to work on this at the moment so you'd have to work on a PR if you want to see this fixed.

**Comment by charmander** [comment]
@ahultgren I’m a bit late to help, but that’s a zero-based array, probably not made intentionally. Arrays in PostgreSQL should start at 1, and this module can only parse 1-based arrays. (There’s no way to make an array with a non-zero base in JavaScript, so if an indexing change needs to be done, it should be done server-side.)

**Comment by bendrucker** [comment]
Hmm, good catch.

```sql
select('[0:2]={1,2,3}'::int[])
# => [0:2]={1,2,3}

select('[1:3]={1,2,3}'::int[])
# => {1,2,3}
```

The left hand side of the expression must have the same length as the right. That presents a problem coming into JS if you want to parse `select('[5:7]={1,2,3}'::int[])`:

```js
const array = []
array[5] = 1
array[6] = 2
array[7] = 3
array.length === 8 // :(
```

Either the indexes match _or_ the length, but not both. This seems like something we need to leave to the user. I'd be open to a PR that discards the indexes, disabled by default. I'm also open to throwing when indexing is detected, by default, in a new major release. Returning a string seems ok for now.
